'use strict';
const $=s=>document.querySelector(s),chat=$('#chat'),choices=$('#choices'),clock=$('#clock');
const KEY='nonaprire_v05_final';
const GAME_START=1*60, GAME_END=48*60, DURATION=(GAME_END-GAME_START)*1000;
const fresh=()=>({v:5,started:false,alive:true,ending:false,startAt:0,scene:'intro',flags:{doorLocked:false,peeked:false,heardVoice:false,proofRequested:false,phoneClue:false,bedroomMarked:false,wallClue:false,callClue:false,stayedQuiet:false},items:[],history:[],loops:0});
let S=fresh(),clockTimer=null,choiceTimer=null,deadlineTimer=null,busy=false;
function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch(_){}}
function scroll(){requestAnimationFrame(()=>chat.scrollTop=chat.scrollHeight)}
function elapsedMs(){return S.started?Math.max(0,Date.now()-S.startAt):0}
function gameSeconds(){return Math.min(GAME_END,GAME_START+Math.floor(elapsedMs()/1000))}
function fmt(sec){const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),ss=sec%60;return String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(ss).padStart(2,'0')}
function updateClock(){clock.textContent=fmt(gameSeconds());if(S.started&&S.alive&&!S.ending&&elapsedMs()>=DURATION)deadlineDeath()}
function startClock(){clearInterval(clockTimer);clockTimer=setInterval(updateClock,250);clearTimeout(deadlineTimer);deadlineTimer=setTimeout(deadlineDeath,Math.max(0,DURATION-elapsedMs()+40));updateClock()}
function notify(text){try{if(document.hidden&&Notification.permission==='granted')new Notification('NUMERO SCONOSCIUTO',{body:text,tag:'na-'+Date.now()})}catch(_){}}
function bubble(text,who='them',delay=0){return new Promise(r=>setTimeout(()=>{if(S.ending&&who!=='sys'){r();return}const d=document.createElement('div');d.className='msg '+who;d.textContent=text;chat.appendChild(d);scroll();if(who==='them')notify(text);r()},delay))}
function clearChoices(){choices.innerHTML='';if(choiceTimer){clearInterval(choiceTimer);choiceTimer=null}}
function buttons(list,timeout){if(S.ending)return;clearChoices();list.filter(c=>!c.if||c.if(S)).forEach(c=>{const b=document.createElement('button');b.className='choice '+(c.action?'action':'');b.textContent=c.label;b.addEventListener('click',()=>choose(c));choices.appendChild(b)});if(timeout){let left=timeout.seconds;const t=document.createElement('div');t.className='timer';t.textContent=`${left}s`;choices.appendChild(t);choiceTimer=setInterval(()=>{left--;t.textContent=`${left}s`;if(left<=4)t.classList.add('danger');if(left<=0){clearInterval(choiceTimer);choiceTimer=null;clearChoices();timeout.run()}},1000)}}
function waitLabel(text='Aspetta…'){clearChoices();const d=document.createElement('div');d.className='waiting';d.textContent=text;choices.appendChild(d)}
async function choose(c){if(busy||S.ending)return;busy=true;clearChoices();S.history.push({scene:S.scene,choice:c.label,at:gameSeconds()});save();await bubble(c.label,'me');busy=false;await c.run()}
async function scene(id){if(S.ending)return;S.scene=id;save();const f=scenes[id];if(f)await f()}
function endingText(){const f=S.flags,sc=S.scene;if(sc.includes('bedroom')||f.bedroomMarked)return 'Alle 00:48 il telefono nella camera comincia a squillare. Il suono si interrompe quando, dall’altra parte della porta, senti il tuo stesso respiro.';if(f.peeked)return 'Alle 00:48 lo spioncino diventa nero. Non perché fuori si sia spenta la luce: qualcosa, dall’interno, ha appoggiato un occhio al vetro.';if(f.callClue)return 'Alle 00:48 il telefono chiama da solo il 112. Risponde la tua voce. Pronuncia il tuo indirizzo. Poi qualcuno bussa da dentro casa.';if(f.wallClue)return 'Alle 00:48 i tre colpi ricominciano nel muro. Questa volta non si spostano lungo il corridoio. Si fermano esattamente dietro di te.';if(f.stayedQuiet)return 'Alle 00:48 il silenzio finisce. Dal corridoio senti un passo, poi un altro. Il numero sconosciuto scrive una sola parola: «Scusa.»';return 'Alle 00:48 tutti i rumori cessano insieme. Il display resta acceso abbastanza da mostrarti un riflesso alle tue spalle.'}
async function deadlineDeath(){if(!S.started||!S.alive||S.ending)return;await die(endingText(),true)}
async function die(text,deadline=false){if(S.ending)return;S.ending=true;S.alive=false;clearChoices();clearTimeout(deadlineTimer);save();await bubble(text,'sys',350);await new Promise(r=>setTimeout(r,1200));showBattery(deadline)}
function showBattery(deadline){const o=$('#overlay');o.classList.remove('hidden');$('#start').classList.add('hidden');$('#notify').classList.add('hidden');$('#restart').classList.add('hidden');$('#battery').classList.remove('hidden');$('#ovTitle').textContent='BATTERIA';$('#ovText').textContent='SCARICA';let left=15;$('#ovSmall').textContent=`Il telefono si spegne tra ${left} secondi…`;const iv=setInterval(()=>{left--;$('#ovSmall').textContent=left>0?`Il telefono si spegne tra ${left} secondi…`:'…';if(left<=0){clearInterval(iv);setTimeout(autoReset,800)}},1000)}
function autoReset(){const loops=(S.loops||0)+1;localStorage.removeItem(KEY);S=fresh();S.loops=loops;save();location.reload()}
const scenes={
intro:async()=>{await bubble('NON APRIRE.','them',650);await bubble('Controlla la porta d’ingresso. Assicurati che sia chiusa a chiave.','them',700);buttons([{label:'Chi sei?',run:()=>scene('whoEarly')},{label:'Perché?',run:()=>scene('why')},{label:'Controllo la porta.',action:true,run:()=>scene('doorCheck')},{label:'Ignoro il messaggio.',action:true,run:()=>scene('ignore')}])},
whoEarly:async()=>{await bubble('Non importa ancora.','them',450);await bubble('Tra poco qualcuno busserà tre volte. Se la porta non è chiusa, non avremo una seconda conversazione.','them',650);buttons([{label:'Come fai a saperlo?',run:()=>scene('howKnow')},{label:'Controllo la porta.',action:true,run:()=>scene('doorCheck')},{label:'Non mi muovo.',action:true,run:()=>scene('ignore')}])},
why:async()=>{await bubble('Perché tra poco sentirai tre colpi.','them',450);await bubble('Qualunque voce sentirai dopo, non aprire.','them',550);buttons([{label:'Controllo la porta.',action:true,run:()=>scene('doorCheck')},{label:'Aspetto i colpi.',action:true,run:()=>scene('waitKnock')},{label:'Chiamo il 112.',action:true,run:()=>scene('callEarly')}])},
howKnow:async()=>{await bubble('Perché ho già aspettato quei tre colpi.','them',550);await bubble('E la prima volta ho aperto.','them',600);buttons([{label:'Chi sei?',run:()=>scene('identityGate')},{label:'Controllo la porta.',action:true,run:()=>scene('doorCheck')},{label:'Aspetto.',action:true,run:()=>scene('waitKnock')}])},
identityGate:async()=>{await bubble('Prima sopravvivi ai prossimi due minuti. Poi ti rispondo.','them',550);buttons([{label:'Controllo la porta.',action:true,run:()=>scene('doorCheck')},{label:'Aspetto i colpi.',action:true,run:()=>scene('waitKnock')}])},
doorCheck:async()=>{S.flags.doorLocked=true;save();await bubble('La chiave è già girata. La porta è chiusa.','sys',400);await bubble('Bene. Ora allontanati.','them',500);await bubble('TOC.  TOC.  TOC.','sys',1200);scene('atDoor')},
waitKnock:async()=>{await bubble('Aspetti.','sys',450);await bubble('TOC.  TOC.  TOC.','sys',1300);await bubble('Adesso sai che non sto indovinando.','them',450);scene('atDoor')},
ignore:async()=>{await bubble('Posi il telefono.','sys',400);await bubble('TOC.  TOC.  TOC.','sys',1400);await bubble('NON APRIRE.','them',300);scene('atDoor')},
callEarly:async()=>{await bubble('Componi il 112. Nessun servizio.','sys',550);await bubble('Non perdere tempo con la rete. Non funziona ancora.','them',450);buttons([{label:'“Ancora?”',run:()=>scene('networkHint')},{label:'Controllo la porta.',action:true,run:()=>scene('doorCheck')},{label:'Apro per vedere chi c’è.',action:true,run:()=>die('La maniglia scende prima che tu riesca a toccarla. La porta si apre verso l’interno.') }])},
networkHint:async()=>{await bubble('Lascia stare quella parola. Controlla la porta.','them',450);buttons([{label:'Controllo la porta.',action:true,run:()=>scene('doorCheck')},{label:'Aspetto.',action:true,run:()=>scene('waitKnock')}])},
atDoor:async()=>{buttons([{label:'Guardo dallo spioncino.',action:true,run:()=>scene('peephole')},{label:'“Chi è?”',run:()=>scene('doorVoice')},{label:'Mi allontano senza parlare.',action:true,run:()=>scene('backAway')},{label:'Apro.',action:true,run:()=>die('Il pianerottolo è vuoto. Poi senti tre colpi provenire dalla porta che hai appena lasciato aperta.') }])},
peephole:async()=>{S.flags.peeked=true;save();await bubble('Il pianerottolo è vuoto.','sys',450);await bubble('Poi sul vetro compare lentamente un alone, come il segno di un respiro.','sys',800);await bubble('Non guardare più. Allontanati.','them',450);buttons([{label:'Mi allontano.',action:true,run:()=>scene('backAway')},{label:'Guardo ancora.',action:true,run:()=>die('Ti avvicini di nuovo allo spioncino. Questa volta, dall’altra parte, c’è già un occhio.') }])},
doorVoice:async()=>{S.flags.heardVoice=true;save();await bubble('«Aprimi.»','sys',650);await bubble('La voce dall’altra parte è la tua.','sys',500);buttons([{label:'Mi allontano.',action:true,run:()=>scene('backAway')},{label:'“Dimmi qualcosa che solo io so.”',run:()=>scene('doorTest')},{label:'Apro.',action:true,run:()=>die('La tua voce sussurra «grazie». La luce del corridoio si spegne prima che tu riesca a vedere cosa entra.') }])},
doorTest:async()=>{await bubble('Silenzio.','sys',650);await bubble('Il numero sconosciuto scrive subito.','sys',450);await bubble('Quella è la domanda giusta. Ma non farla a lui.','them',500);S.flags.proofRequested=true;save();buttons([{label:'“Allora la faccio a te. Chi sei?”',run:()=>scene('identity')},{label:'Mi allontano dalla porta.',action:true,run:()=>scene('backAway')}])},
backAway:async()=>{await bubble('Dal fondo della casa arrivano tre colpi.','sys',800);await bubble('Questa volta dalla camera da letto.','sys',550);await bubble('Non andare lì.','them',400);buttons([{label:'Come sapevi che si sarebbero spostati?',run:()=>scene('livedIt')},{label:'Dimmi chi sei.',run:()=>scene('identity')},{label:'Mi avvicino alla camera senza entrare.',action:true,run:()=>scene('bedroomDoor')},{label:'Mi chiudo in bagno.',action:true,run:()=>scene('bathroom')}])},
identity:async()=>{await bubble('Se ti rispondo adesso non mi crederai.','them',500);await bubble('Prima lascia che ti dimostri una cosa che non potrei sapere.','them',550);buttons([{label:'Va bene. Dimostralo.',run:()=>scene('prove')},{label:'No. Rispondi alla domanda.',run:()=>scene('nameNow')},{label:'Ignoro il messaggio e mi avvicino alla camera.',action:true,run:()=>scene('bedroomDoor')}])},
livedIt:async()=>{await bubble('Perché prima erano alla porta. Adesso sono in camera.','them',600);await bubble('So quale sarà il prossimo posto, se continuiamo a fare le stesse cose.','them',600);buttons([{label:'Qual è il prossimo posto?',run:()=>scene('change')},{label:'Allora dimmi chi sei.',run:()=>scene('identity')},{label:'Mi avvicino alla camera senza entrare.',action:true,run:()=>scene('bedroomDoor')}])},
nameNow:async()=>{await bubble('Sono te.','them',650);await bubble('Non quello che sei adesso. Quello che resta dopo che questa notte ricomincia.','them',700);buttons([{label:'Non ti credo. Provalo.',run:()=>scene('prove')},{label:'Come puoi scrivermi?',run:()=>scene('howMessage')},{label:'Mi avvicino alla camera.',action:true,run:()=>scene('bedroomDoor')}])},
prove:async()=>{await bubble('Guarda il telefono che hai in mano. Angolo superiore, vicino alla fotocamera.','them',550);await bubble('C’è una crepa sottile nella cover. Tu non ricordi di averla fatta.','them',650);buttons([{label:'Controllo la cover.',action:true,run:()=>scene('phoneProof')},{label:'Potresti semplicemente vedermi.',run:()=>scene('notWatching')},{label:'Non controllo. Mi avvicino alla camera.',action:true,run:()=>scene('bedroomDoor')}])},
notWatching:async()=>{await bubble('Se potessi vederti, ti direi cosa c’è dietro di te. Non posso.','them',550);await bubble('Posso solo ricordare cosa c’era quando ero al tuo posto.','them',600);buttons([{label:'Controllo la cover.',action:true,run:()=>scene('phoneProof')},{label:'“Allora chi sei?”',run:()=>scene('nameNow')}])},
phoneProof:async()=>{S.flags.phoneClue=true;save();await bubble('La crepa c’è. Non la riconosci.','sys',500);await bubble('Il tuo vero telefono è nella camera. Non entrare per prenderlo.','them',600);buttons([{label:'Come faccio a verificare che sia lì?',run:()=>scene('verifyBedroom')},{label:'Perché questo telefono è qui?',run:()=>scene('howMessage')},{label:'Entro comunque.',action:true,run:()=>scene('bedroomEnter')}])},
howMessage:async()=>{await bubble('Non lo so ancora. So soltanto che i messaggi arrivano prima di quando li invio.','them',650);await bubble('E che ogni volta che provo a cambiare troppo le cose, qualcosa cambia con me.','them',650);buttons([{label:'Come verifico il telefono in camera?',run:()=>scene('verifyBedroom')},{label:'Cosa succede dopo?',run:()=>scene('change')},{label:'Entro in camera.',action:true,run:()=>scene('bedroomEnter')}])},
verifyBedroom:async()=>{await bubble('Non aprire la porta. Avvicinati soltanto abbastanza da ascoltare.','them',500);buttons([{label:'Mi avvicino alla camera.',action:true,run:()=>scene('bedroomDoor')},{label:'Resto dove sono.',action:true,run:()=>scene('change')}])},
bedroomDoor:async()=>{S.flags.bedroomMarked=true;save();await bubble('Ti fermi davanti alla camera chiusa.','sys',450);await bubble('Dall’interno parte una suoneria. È la tua.','sys',850);await bubble('Adesso sai che non hai in mano il tuo telefono.','them',500);buttons([{label:'Entro a prenderlo.',action:true,run:()=>scene('bedroomEnter')},{label:'Busso alla porta.',action:true,run:()=>scene('bedroomKnock')},{label:'Mi allontano.',action:true,run:()=>scene('change')}])},
bedroomEnter:async()=>{await bubble('Apri la porta. Il tuo telefono è acceso sul letto.','sys',650);await bubble('Sul suo schermo c’è un solo messaggio: «NON GIRARTI.»','sys',750);buttons([{label:'Resto immobile.',action:true,run:()=>scene('freezeBedroom')},{label:'Mi giro.',action:true,run:()=>die('Ti giri. La stanza è vuota. Sul letto, però, adesso ci sono due telefoni. Entrambi stanno fotografando qualcosa dietro di te.')},{label:'Prendo il mio telefono.',action:true,run:()=>die('Appena tocchi il telefono sul letto, quello che hai in mano vibra: «Troppo tardi.»') }],{seconds:12,run:()=>scene('freezeBedroom')})},
freezeBedroom:async()=>{await bubble('Non ti muovi.','sys',600);await bubble('Qualcosa passa dietro di te senza fare rumore. Lo capisci solo perché il materasso si abbassa per un istante.','sys',900);await bubble('Esci senza prendere nulla.','them',450);buttons([{label:'Esco senza voltarmi.',action:true,run:()=>scene('hall')},{label:'Prendo il telefono e corro.',action:true,run:()=>die('Afferri il telefono. La porta della camera si chiude. Dall’esterno, qualcuno comincia a bussare tre volte.') }])},
bedroomKnock:async()=>{await bubble('Bussi una volta.','sys',450);await bubble('Dall’interno rispondono due colpi.','sys',700);await bubble('Non completare la sequenza. Allontanati.','them',400);buttons([{label:'Mi allontano.',action:true,run:()=>scene('change')},{label:'Busso altre due volte.',action:true,run:()=>die('Completi tre colpi. La maniglia della camera scende lentamente dall’interno.') }])},
bathroom:async()=>{await bubble('Chiudi la porta del bagno.','sys',450);await bubble('Per qualche secondo non succede nulla.','sys',750);await bubble('Poi lo specchio si appanna dall’interno.','sys',650);buttons([{label:'Esco subito.',action:true,run:()=>scene('change')},{label:'Guardo lo specchio.',action:true,run:()=>scene('mirror')}])},
mirror:async()=>{await bubble('Sulla condensa compare: 00:48.','sys',700);await bubble('Non l’avevo mai visto così presto. Esci.','them',500);S.flags.wallClue=true;save();buttons([{label:'Esco.',action:true,run:()=>scene('change')},{label:'Tocco lo specchio.',action:true,run:()=>die('Il vetro è caldo. Dall’altra parte, qualcosa appoggia il palmo esattamente contro il tuo.') }])},
change:async()=>{await bubble('Tra poco salterà la corrente. Dopo sentirai i colpi dentro il muro.','them',600);await bubble('Questa volta non rispondere ai colpi.','them',550);buttons([{label:'Perché?',run:()=>scene('whyWall')},{label:'Cerco una torcia.',action:true,run:()=>scene('hall')},{label:'Aspetto al buio.',action:true,run:()=>scene('hall')}])},
whyWall:async()=>{await bubble('Perché una volta ho risposto. Da quel momento ha iniziato a sapere dove mi trovavo.','them',650);buttons([{label:'Aspetto.',action:true,run:()=>scene('hall')},{label:'“E alle 00:48?”',if:s=>s.flags.wallClue,run:()=>scene('fortyEightHint')}])},
fortyEightHint:async()=>{await bubble('Non sono mai riuscito a impedirlo.','them',600);await bubble('Ma ogni volta accade in modo diverso. Credo che dipenda da quello che facciamo prima.','them',650);scene('hall')},
hall:async()=>{waitLabel('Il telefono resta acceso. L’orologio continua.');await bubble('La corrente salta.','sys',1500);await bubble('Toc.','sys',900);await bubble('Toc.','sys',500);await bubble('Toc.','sys',500);await bubble('I colpi arrivano dall’interno della parete.','sys',650);scene('wall')},
wall:async()=>{buttons([{label:'Resto in silenzio.',action:true,run:()=>scene('silent')},{label:'Appoggio il telefono al muro.',action:true,run:()=>scene('wallPhone')},{label:'Busso tre volte.',action:true,run:()=>scene('knockBack')},{label:'Provo a chiamare il 112.',action:true,run:()=>scene('callLate')}])},
silent:async()=>{S.flags.stayedQuiet=true;save();await bubble('Non rispondi.','sys',500);await bubble('I colpi si spostano lungo la parete, poi si fermano.','sys',850);await bubble('Bene. Questa parte è diversa.','them',500);scene('longGame')},
wallPhone:async()=>{S.flags.wallClue=true;save();await bubble('Appoggi il telefono al muro.','sys',450);await bubble('Lo schermo lampeggia: 00:48 → 00:01.','sys',750);await bubble('Toglilo da lì. Adesso.','them',350);buttons([{label:'Lo tolgo.',action:true,run:()=>scene('longGame')},{label:'Lo lascio contro il muro.',action:true,run:()=>die('Lo schermo si spegne. Dal muro arriva la vibrazione di una chiamata in entrata. Poi la senti nella tua mano.') }])},
knockBack:async()=>{await bubble('Bussi tre volte.','sys',450);await bubble('Quattro colpi rispondono immediatamente.','sys',650);await bubble('Ti avevo detto di non rispondere. Spostati.','them',350);buttons([{label:'Mi sposto.',action:true,run:()=>scene('longGame')},{label:'Busso quattro volte.',action:true,run:()=>die('Rispondi con quattro colpi. Dalla parete ne arriva uno solo, fortissimo. L’intonaco si spacca verso l’esterno.') }])},
callLate:async()=>{S.flags.callClue=true;save();await bubble('La chiamata parte.','sys',500);await bubble('«Emergenze. Dica pure.»','sys',600);await bubble('NON DIRE DOVE SEI.','them',250);buttons([{label:'“Qual è il mio numero?”',run:()=>scene('callTest')},{label:'Do il mio indirizzo.',run:()=>die('«Lo sappiamo già», risponde la voce. Tre colpi arrivano dalla parete alle tue spalle.')},{label:'Riattacco.',action:true,run:()=>scene('longGame')}])},
callTest:async()=>{await bubble('La voce dall’altra parte recita il numero del telefono che hai in mano.','sys',700);await bubble('Poi aggiunge: «Ma questo numero non esiste ancora.»','sys',650);await bubble('Riattacca.','them',300);buttons([{label:'Riattacco.',action:true,run:()=>scene('longGame')}])},
longGame:async()=>{await bubble('Bene. I colpi si sono fermati.','them',600);await bubble('Non muoverti a caso. Dimmi cosa senti.','them',600);buttons([{label:'“Niente. È tutto fermo.”',run:()=>scene('plan')},{label:'“Prima hai detto che questa parte era diversa. Perché?”',run:()=>scene('finalIdentity')},{label:'Non rispondo. Controllo la casa.',action:true,run:()=>scene('hold')}])},
finalIdentity:async()=>{await bubble('Perché di solito, a questo punto, i colpi continuano.','them',600);await bubble('Stavolta hai fatto qualcosa che io non avevo fatto.','them',650);buttons([{label:'“Quindi posso cambiare quello che succede?”',run:()=>scene('plan')},{label:'Resto in silenzio e ascolto.',action:true,run:()=>scene('hold')}])},
plan:async()=>{await bubble('Sì. Ma ogni cambiamento sembra spostare qualcos’altro.','them',650);await bubble('Per ora: niente sequenze di colpi. E se senti la tua voce, non seguirla.','them',650);scene('hold')},
hold:async()=>{S.flags.stayedQuiet=true;save();await bubble('Per qualche secondo la casa resta immobile.','sys',650);buttons([{label:'Controllo il corridoio.',action:true,run:()=>scene('corridorWatch')},{label:'Cerco da dove arrivavano i colpi.',action:true,run:()=>scene('wallSearch')},{label:'Resto fermo e ascolto.',action:true,run:()=>scene('listenAgain')}])},
corridorWatch:async()=>{await bubble('Il corridoio è vuoto. La porta della camera è socchiusa. Prima era chiusa.','sys',700);buttons([{label:'La richiudo senza entrare.',action:true,run:()=>scene('doorMoves')},{label:'Guardo dentro senza entrare.',action:true,run:()=>scene('bedroomGlance')},{label:'Torno indietro.',action:true,run:()=>scene('listenAgain')}])},
doorMoves:async()=>{await bubble('Spingi la porta con due dita.','sys',500);await bubble('Prima che tocchi il battente, la porta si chiude da sola.','sys',750);await bubble('Non aprirla.','them',350);buttons([{label:'“L’hai visto anche tu?”',run:()=>scene('afterDoorMove')},{label:'Mi allontano.',action:true,run:()=>scene('listenAgain')}])},
afterDoorMove:async()=>{await bubble('No. Ma è successo anche a me. Più tardi.','them',600);await bubble('Stiamo anticipando qualcosa.','them',500);buttons([{label:'“Cosa?”',run:()=>scene('listenAgain')},{label:'Controllo il muro.',action:true,run:()=>scene('wallSearch')}])},
bedroomGlance:async()=>{await bubble('Dentro è buio. Sul letto c’è una luce rettangolare: uno schermo acceso.','sys',700);await bubble('Non entrare.','them',300);buttons([{label:'Mi allontano.',action:true,run:()=>scene('listenAgain')},{label:'Entro solo per vedere lo schermo.',action:true,run:()=>scene('bedroomEnter')}])},
wallSearch:async()=>{await bubble('Avvicini l’orecchio alla parete.','sys',500);await bubble('Niente colpi. Solo un ronzio basso, come un telefono in vibrazione molto lontano.','sys',750);buttons([{label:'Appoggio il telefono al muro.',action:true,run:()=>scene('wallPhone')},{label:'Mi allontano.',action:true,run:()=>scene('listenAgain')}])},
listenAgain:async()=>{await bubble('Aspetti.','sys',500);await bubble('Dal piano di sopra arriva il rumore di una sedia trascinata.','sys',900);await bubble('Tu non hai un piano di sopra.','them',450);buttons([{label:'Guardo il soffitto.',action:true,run:()=>scene('ceiling')},{label:'Ignoro il rumore e controllo il corridoio.',action:true,run:()=>scene('corridorWatch')},{label:'“Cosa c’è sopra di me?”',run:()=>scene('ceilingQuestion')}])},
ceilingQuestion:async()=>{await bubble('Nel mio appartamento? Niente.','them',550);await bubble('Ed è questo il problema.','them',450);scene('ceiling')},
ceiling:async()=>{await bubble('Una linea sottile compare sull’intonaco del soffitto.','sys',650);await bubble('Si allunga lentamente fino a fermarsi sopra di te.','sys',750);buttons([{label:'Mi sposto subito.',action:true,run:()=>scene('afterCeiling')},{label:'Resto sotto la crepa.',action:true,run:()=>die('Dalla crepa cade polvere. Poi qualcosa bussa tre volte dall’altra parte del soffitto. Al terzo colpo, l’intonaco si piega verso il basso.') }])},
afterCeiling:async()=>{await bubble('Ti sposti. La crepa smette di avanzare.','sys',600);await bubble('Il telefono vibra. Nessun messaggio.','sys',550);buttons([{label:'Controllo il corridoio.',action:true,run:()=>scene('corridorWatch')},{label:'Controllo il muro.',action:true,run:()=>scene('wallSearch')},{label:'Resto fermo e ascolto.',action:true,run:()=>scene('listenAgain')}])},
};
let atmosphereTimers=[];
function scheduleAtmosphere(){atmosphereTimers.forEach(clearTimeout);atmosphereTimers=[];const marks=[12,24,36,43];const texts=['Da qualche parte in casa, qualcosa trascina lentamente un oggetto sul pavimento.','Il telefono vibra senza mostrare alcun nuovo messaggio.','Per un istante senti una seconda vibrazione provenire dalla camera da letto.','NUMERO SCONOSCIUTO: «Qualunque cosa succeda tra poco, guarda dove sei. Ricordatelo.»'];marks.forEach((m,i)=>{const target=(m*60-GAME_START)*1000;const delay=target-elapsedMs();if(delay>0)atmosphereTimers.push(setTimeout(()=>{if(S.alive&&!S.ending)bubble(texts[i],i===3?'them':'sys')},delay))})}
async function start(){if(S.started)return;S.started=true;S.startAt=Date.now();save();$('#overlay').classList.add('hidden');startClock();await scene('intro')}
function manualReset(){localStorage.removeItem(KEY);location.reload()}
$('#start').addEventListener('click',start);$('#restart').addEventListener('click',manualReset);$('#notify').addEventListener('click',async()=>{try{if(!('Notification'in window))throw 0;const p=await Notification.requestPermission();$('#notify').textContent=p==='granted'?'NOTIFICHE ATTIVE':'NOTIFICHE NON DISPONIBILI'}catch(_){$('#notify').textContent='NOTIFICHE NON DISPONIBILI'}});
window.addEventListener('error',e=>{const d=document.createElement('div');d.className='msg sys danger';d.textContent='Errore interno: '+e.message;chat.appendChild(d)});
try{const old=JSON.parse(localStorage.getItem(KEY));if(old&&old.v===5){S=old;if(S.started&&S.alive&&!S.ending){$('#overlay').classList.add('hidden');startClock();bubble('PARTITA RIPRISTINATA','sys').then(()=>scene(S.scene));if(S.scene==='hold')scheduleAtmosphere()}else if(S.ending||!S.alive){localStorage.removeItem(KEY);S=fresh()}}}catch(_){S=fresh()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});
