'use strict';
const $=s=>document.querySelector(s), chat=$('#chat'), choices=$('#choices'), clock=$('#clock');
const KEY='nonaprire_v09_state', META='nonaprire_v09_meta';
const START=60, END=48*60, LIMIT=(END-START)*1000;
let S={started:false,alive:true,ending:false,chapterDone:false,startAt:0,node:'intro',history:[],loops:0};
let clockTimer=null, deadlineTimer=null, busy=false, deathTimer=null;
try{const m=JSON.parse(localStorage.getItem(META));if(m&&Number.isFinite(m.loops))S.loops=m.loops}catch(_){}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch(_){}}
function elapsed(){return S.started?Math.max(0,Date.now()-S.startAt):0}
function gameSec(){return Math.min(END,START+Math.floor(elapsed()/1000))}
function fmt(n){const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return [h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
function updateClock(){clock.textContent=fmt(gameSec());if(S.started&&S.alive&&!S.ending&&!S.chapterDone&&elapsed()>=LIMIT)deadlineDeath()}
function startClock(){clearInterval(clockTimer);clearTimeout(deadlineTimer);clockTimer=setInterval(updateClock,250);deadlineTimer=setTimeout(deadlineDeath,Math.max(0,LIMIT-elapsed()+50));updateClock()}
function stopTimers(){clearInterval(clockTimer);clearTimeout(deadlineTimer);if(deathTimer)clearInterval(deathTimer);clockTimer=deadlineTimer=deathTimer=null}
function scrollBottom(){requestAnimationFrame(()=>chat.scrollTop=chat.scrollHeight)}
function add(text,who='sys',delay=0){return new Promise(resolve=>setTimeout(()=>{if(!text){resolve();return}const d=document.createElement('div');d.className='msg '+who;d.textContent=text;chat.appendChild(d);scrollBottom();resolve()},delay))}
function clearChoices(){choices.replaceChildren()}
function renderChoices(list){clearChoices();if(S.ending||S.chapterDone)return;for(const c of list){const b=document.createElement('button');b.type='button';b.className='choice '+(c.action?'action':'');b.textContent=c.label;b.addEventListener('click',()=>pick(c),{once:true});choices.appendChild(b)}}
async function pick(c){if(busy||S.ending||S.chapterDone)return;busy=true;const label=c.label;clearChoices();S.history.push({node:S.node,choice:label,at:gameSec()});save();await add(label,'me',0);if(c.death){busy=false;return die(c.death)}if(c.end){busy=false;return chapterEnd()}busy=false;return go(c.next)}
async function go(id){if(S.ending||S.chapterDone)return;const node=NODES[id];if(!node){return failSafe('Il filo della conversazione si interrompe. Il telefono vibra una volta, poi compare un nuovo messaggio.')}S.node=id;save();clearChoices();for(const m of node.msgs){await add(m.text,m.who||'sys',m.delay??420)}if(node.end)return chapterEnd();if(!node.choices||node.choices.length===0)return failSafe('Per qualche secondo non succede nulla. Poi il numero sconosciuto scrive di nuovo.');renderChoices(node.choices)}
async function failSafe(text){await add(text,'sys',500);await add('Non restare fermo. Vai verso l’ingresso.','them',450);renderChoices([{label:'Vado verso l’ingresso.',action:true,next:'entry_final'},{label:'Resto dove sono e ascolto.',action:true,next:'listen_final'}])}
function contextualDeadline(){const n=S.node;if(/bed|room|mirror/.test(n))return 'Alle 00:48 lo schermo nella camera si accende. Nel vetro nero compare il tuo riflesso, ma continua a muoversi quando tu ti fermi.';if(/door|entry/.test(n))return 'Alle 00:48 la serratura scatta. Non dall’esterno. La porta si apre lentamente verso di te e, dietro, c’è il corridoio di casa tua.';if(/wall|listen|ceiling/.test(n))return 'Alle 00:48 i colpi tornano. Non arrivano più dalla parete: arrivano da dentro il telefono che tieni in mano.';return 'Alle 00:48 tutti i rumori cessano. Nel display vedi per un istante qualcuno fermo esattamente alle tue spalle.'}
async function deadlineDeath(){if(!S.started||!S.alive||S.ending||S.chapterDone)return;await die(contextualDeadline())}
async function die(text){if(S.ending||S.chapterDone)return;S.ending=true;S.alive=false;clearChoices();clearTimeout(deadlineTimer);save();await add(text,'sys',450);const box=document.createElement('div');box.className='deadBattery';box.innerHTML='<div class="deadBatteryRow"><span class="deadBatteryIcon" aria-hidden="true">🪫</span><div><strong>BATTERIA SCARICA</strong><span>0%</span></div></div><p class="deathCountdown">Il loop ricomincia tra <b>15</b> secondi…</p><small>Puoi scorrere la chat e rileggere cosa è successo.</small>';chat.appendChild(box);scrollBottom();let left=15;const n=box.querySelector('b');deathTimer=setInterval(()=>{left--;if(n)n.textContent=Math.max(0,left);if(left<=0){clearInterval(deathTimer);deathTimer=null;resetLoop()}},1000)}
async function chapterEnd(){if(S.chapterDone||S.ending)return;S.chapterDone=true;clearChoices();stopTimers();save();await add('Il telefono smette di vibrare. Per la prima volta dall’inizio della notte, il silenzio non sembra una minaccia.','sys',600);const box=document.createElement('div');box.className='chapterEnd';box.innerHTML='<strong>CAPITOLO 1 COMPLETATO</strong><p>Hai raggiunto la fine del contenuto disponibile.</p><small>Il Capitolo 2 è ancora in sviluppo.</small>';chat.appendChild(box);scrollBottom();const b=document.createElement('button');b.type='button';b.className='choice';b.textContent='RICOMINCIA IL CAPITOLO 1';b.addEventListener('click',resetLoop,{once:true});choices.appendChild(b)}
function resetLoop(){stopTimers();const loops=(S.loops||0)+1;try{localStorage.setItem(META,JSON.stringify({loops}))}catch(_){}localStorage.removeItem(KEY);location.reload()}
function resetAll(){stopTimers();localStorage.removeItem(KEY);localStorage.removeItem(META);location.reload()}
const C=(label,next,action=false)=>({label,next,action});
const D=(label,death,action=true)=>({label,death,action});
const M=(text,who='sys',delay=420)=>({text,who,delay});
const NODES={
intro:{msgs:[M('NON APRIRE.','them',650),M('Controlla la porta d’ingresso. Assicurati che sia chiusa.','them',650)],choices:[C('“Chi sei?”','who'),C('“Perché?”','why'),C('Controllo la porta.','door_check',true),C('Ignoro il messaggio.','ignore',true)]},
who:{msgs:[M('Non importa ancora.','them'),M('Tra poco sentirai tre colpi. Se la porta non è chiusa, non avremo molto tempo.','them',600)],choices:[C('“Come fai a saperlo?”','knows'),C('Controllo la porta.','door_check',true),C('Aspetto i colpi.','wait_knock',true)]},
why:{msgs:[M('Perché tra poco sentirai tre colpi.','them'),M('Qualunque voce sentirai dopo, non aprire.','them')],choices:[C('Controllo la porta.','door_check',true),C('Aspetto i colpi.','wait_knock',true),C('Provo a chiamare il 112.','call_112',true)]},
knows:{msgs:[M('Perché li ho già aspettati.','them'),M('La prima volta ho aperto.','them',550)],choices:[C('“La prima volta?”','first_time'),C('Controllo la porta.','door_check',true)]},
first_time:{msgs:[M('Non posso spiegartelo in un messaggio.','them'),M('Prima ascolta i colpi. Poi decidi se credermi.','them')],choices:[C('Controllo la porta.','door_check',true),C('Resto fermo e aspetto.','wait_knock',true)]},
call_112:{msgs:[M('Nessun servizio.','sys'),M('Il numero sconosciuto scrive prima che tu possa riprovare.','sys'),M('La rete non ti aiuterà stanotte.','them')],choices:[C('“Come lo sai?”','knows'),C('Controllo la porta.','door_check',true),D('Apro la porta e cerco aiuto.','La maniglia scende prima che tu riesca a toccarla. La porta si apre verso l’interno. Dall’altra parte non c’è il pianerottolo.') ]},
door_check:{msgs:[M('La porta è chiusa a chiave.','sys'),M('TOC.  TOC.  TOC.','sys',1100),M('Allontanati dalla porta.','them')],choices:[C('Guardo dallo spioncino.','peephole',true),C('“Chi è?”','voice'),C('Mi allontano in silenzio.','back_away',true)]},
wait_knock:{msgs:[M('Aspetti.','sys'),M('TOC.  TOC.  TOC.','sys',1200),M('Adesso sai che non stavo indovinando.','them')],choices:[C('Guardo dallo spioncino.','peephole',true),C('“Chi è?”','voice'),C('Mi allontano in silenzio.','back_away',true)]},
ignore:{msgs:[M('Posi il telefono.','sys'),M('TOC.  TOC.  TOC.','sys',1200),M('Il telefono vibra di nuovo.','sys'),M('NON APRIRE.','them')],choices:[C('Guardo dallo spioncino.','peephole',true),C('Mi allontano dalla porta.','back_away',true),D('Apro e faccio finire questa storia.','La porta si apre senza resistenza. Sul pianerottolo non c’è nessuno. Poi senti la porta chiudersi alle tue spalle.') ]},
peephole:{msgs:[M('Avvicini l’occhio allo spioncino.','sys'),M('Il pianerottolo è vuoto. Ma la luce davanti alla tua porta è spenta. Tutte le altre sono accese.','sys',650),M('Non guardare una seconda volta.','them')],choices:[C('Mi allontano.','hall_a',true),C('“Perché non devo guardare?”','proof'),D('Guardo di nuovo.','Lo spioncino è completamente nero. Poi qualcosa batte tre volte sul vetro, dall’interno.') ]},
voice:{msgs:[M('“Chi è?”','sys'),M('Dall’altra parte arriva la tua voce.','sys',700),M('«Sono io. Aprimi.»','sys',600),M('Non risponderle.','them')],choices:[C('Mi allontano senza parlare.','hall_a',true),C('“Sei tu quello fuori?”','proof'),D('“Dimmi qualcosa che solo io so.”','La voce dietro la porta risponde con una frase che ricordi di aver pensato, ma mai detto. La serratura scatta.') ]},
back_away:{msgs:[M('Ti allontani. I colpi cessano.','sys'),M('Dal fondo della casa arriva una vibrazione breve.','sys',700)],choices:[C('Controllo il corridoio.','hall_a',true),C('“Adesso dimmi chi sei.”','proof')]},
proof:{msgs:[M('Se te lo dicessi adesso, penseresti che sto mentendo.','them'),M('Vai in bagno. Guarda lo specchio, ma non accendere la luce.','them',600)],choices:[C('Vado in bagno.','bathroom',true),C('Non mi fido. Controllo il corridoio.','hall_a',true)]},
hall_a:{msgs:[M('Il corridoio è vuoto.','sys'),M('La porta della camera da letto è socchiusa. Prima era chiusa.','sys',650)],choices:[C('Guardo dentro senza entrare.','bed_glance',true),C('Vado in bagno.','bathroom',true),C('Cerco da dove arriva la vibrazione.','wall',true)]},
bathroom:{msgs:[M('Il bagno è buio. Nello specchio distingui appena il tuo viso.','sys'),M('Il telefono vibra.','sys'),M('Guarda la tua mano sinistra.','them')],choices:[C('Guardo la mano.','hand',true),C('Esco subito dal bagno.','hall_b',true)]},
hand:{msgs:[M('Sul polso c’è un graffio sottile che non ricordi di esserti fatto.','sys'),M('Sul bordo dello specchio, nella condensa, qualcuno ha scritto: “NON È LA PRIMA”.','sys',700)],choices:[C('“Sei stato tu?”','identity'),C('Esco e controllo la camera.','bed_glance',true)]},
identity:{msgs:[M('Sì. Ma non stanotte.','them'),M('Sono te. Non quello che sei adesso.','them',650),M('Non devi credermi. Devi solo ricordare quello che vedi.','them')],choices:[C('“Cosa devo ricordare?”','remember'),C('Non gli credo. Esco dal bagno.','hall_b',true)]},
remember:{msgs:[M('Quale porta cambia posizione. Da dove arrivano i colpi. E cosa stai facendo quando l’orologio smette di essere dalla tua parte.','them')],choices:[C('Controllo la camera da letto.','bed_glance',true),C('Cerco la vibrazione nel muro.','wall',true)]},
wall:{msgs:[M('Appoggi l’orecchio alla parete.','sys'),M('Senti un ronzio basso, come un telefono in vibrazione molto lontano.','sys',650),M('Poi tre colpi si spostano lungo il muro, verso la camera.','sys',700)],choices:[C('Seguo i colpi.','bed_glance',true),C('Mi sposto nella direzione opposta.','hall_b',true),C('Appoggio il telefono alla parete.','wall_phone',true)]},
wall_phone:{msgs:[M('Appoggi il telefono al muro.','sys'),M('Lo schermo si accende da solo. Per un istante compare una chiamata in uscita verso il tuo stesso numero.','sys',700),M('La chiamata termina prima che tu possa toccare nulla.','sys')],choices:[C('Vado verso la camera.','bed_glance',true),C('Vado verso l’ingresso.','entry_final',true)]},
bed_glance:{msgs:[M('Dalla soglia vedi il letto.','sys'),M('Sopra le coperte c’è un secondo telefono acceso.','sys',650),M('Sul suo schermo è aperta la stessa conversazione.','sys',600)],choices:[C('Resto sulla soglia e leggo lo schermo.','second_phone',true),C('Mi allontano dalla camera.','hall_b',true),D('Entro e prendo il secondo telefono.','Appena tocchi il secondo telefono, quello nella tua mano si spegne. Dal corridoio arriva la tua voce: «Finalmente.»') ]},
second_phone:{msgs:[M('Sullo schermo dell’altro telefono c’è un messaggio non ancora arrivato sul tuo.','sys'),M('«Quando senti la sedia, non guardare in alto.»','sys',650),M('Un secondo dopo, dal soffitto arriva il rumore di una sedia trascinata.','sys',850)],choices:[C('Non guardo in alto e torno nel corridoio.','hall_b',true),C('“Cosa c’è sopra di me?”','ceiling_answer'),D('Guardo il soffitto.','Una crepa compare esattamente sopra di te. Si apre come una palpebra. Qualcosa dall’altra parte guarda giù.') ]},
ceiling_answer:{msgs:[M('Nel mio appartamento non c’era niente.','them'),M('Nel tuo, adesso, non ne sono più sicuro.','them',600)],choices:[C('Mi allontano dalla camera.','hall_b',true),C('Vado verso l’ingresso.','entry_final',true)]},
hall_b:{msgs:[M('Le luci del corridoio si spengono una alla volta.','sys'),M('L’ultima rimasta accesa è quella vicino all’ingresso.','sys',700),M('Il numero sconosciuto scrive una sola frase.','sys'),M('Adesso scegli dove vuoi essere quando cambia tutto.','them')],choices:[C('Vado verso l’ingresso.','entry_final',true),C('Resto nel corridoio e ascolto.','listen_final',true),C('Torno davanti alla camera.','room_final',true),C('Torno alla parete da cui arrivava la vibrazione.','wall_final',true),C('Torno davanti allo specchio del bagno.','mirror_final',true)]},
entry_final:{msgs:[M('Raggiungi l’ingresso. La porta è ancora chiusa.','sys'),M('Sotto la porta scivola lentamente un foglio.','sys',700),M('È una fotografia del tuo corridoio. È stata scattata da dietro di te.','sys',700)],choices:[C('Non mi volto. Fotografo a mia volta il foglio.','entry_evidence',true),D('Mi volto subito.','Il corridoio è vuoto. Nella fotografia, invece, ora sei girato verso l’obiettivo. E qualcuno è dietro di te.'),C('“Cosa devo fare con questa foto?”','entry_evidence')]},
entry_evidence:{msgs:[M('Salvi la prova sul telefono.','sys'),M('Per alcuni secondi non succede nulla.','sys',650),M('Poi il numero sconosciuto invia un file.','sys'),M('È la stessa fotografia che hai appena creato. Ma il timestamp è di domani.','them',700)],choices:[C('“Quindi domani sarò ancora qui?”','entry_truth'),C('“Come hai questa foto?”','entry_truth')]},
entry_truth:{msgs:[M('Non lo so.','them'),M('So solo che ogni volta riesco a mandarti qualcosa un po’ prima.','them',600),M('Questa volta sei arrivato più lontano di me.','them',650),M('Conserva la foto. Se la notte ricomincia, non partire da zero.','them')],choices:[C('Continuo a leggere.','entry_close',true)]},
entry_close:{msgs:[M('La fotografia resta nella galleria.','sys'),M('Quando torni alla chat, il numero sconosciuto non è più online.','sys',650),M('La porta rimane chiusa. Per ora.','sys')],end:true},
listen_final:{msgs:[M('Rimani fermo.','sys'),M('Senti due respirazioni: la tua e una seconda, sincronizzata con mezzo secondo di ritardo.','sys',750),M('Quando trattieni il fiato, l’altra continua.','sys',650)],choices:[C('Registro il suono con il telefono.','listen_evidence',true),D('Chiamo ad alta voce chiunque sia lì.','La seconda respirazione si interrompe. Una voce, vicinissima al tuo orecchio, risponde: «Eccomi.»'),C('Resto immobile e continuo ad ascoltare.','listen_deeper',true)]},
listen_deeper:{msgs:[M('Non ti muovi.','sys'),M('La seconda respirazione si allontana di qualche passo.','sys',650),M('Poi senti la tua voce, molto più avanti nel corridoio, sussurrare: «Registrami.»','sys',700)],choices:[C('Avvio la registrazione senza parlare.','listen_evidence',true),D('Seguo la mia voce nel buio.','Fai tre passi. Al quarto, il pavimento sotto il piede non c’è più. Eppure il corridoio davanti a te continua.') ]},
listen_evidence:{msgs:[M('Avvii la registrazione.','sys'),M('Sul display l’onda sonora continua anche quando la casa è completamente silenziosa.','sys',650),M('Il file si salva con una durata impossibile: -00:01.','sys',650),M('Il numero sconosciuto ti invia lo stesso audio. Il suo file è datato domani.','them')],choices:[C('“L’hai già sentito?”','listen_truth'),C('“Perché la durata è negativa?”','listen_truth')]},
listen_truth:{msgs:[M('Perché non sta registrando quello che succede adesso.','them'),M('Sta registrando qualcosa che deve ancora arrivare.','them',650),M('Conservalo. Se ricominci, ascoltalo prima che la casa diventi silenziosa.','them')],choices:[C('Salvo il file.','listen_close',true)]},
listen_close:{msgs:[M('Metti il telefono in tasca senza interrompere la registrazione.','sys'),M('Per la prima volta la seconda respirazione si ferma.','sys',700),M('Il corridoio resta buio, ma non sei più costretto a seguirlo.','sys')],end:true},
room_final:{msgs:[M('Torni davanti alla camera. Il secondo telefono non è più sul letto.','sys'),M('Adesso è sul pavimento del corridoio, alle tue spalle.','sys',700)],choices:[C('Non lo tocco. Scatto una foto.','room_evidence',true),D('Raccolgo il secondo telefono.','Lo schermo mostra la tua chat un messaggio avanti. Leggi: «Non raccoglierlo.» Poi senti le dita chiudersi attorno al tuo polso.'),C('Resto sulla soglia e osservo lo schermo da lontano.','room_watch',true)]},
room_watch:{msgs:[M('Lo schermo del secondo telefono si accende.','sys'),M('La chat scorre da sola fino a un messaggio che sul tuo telefono non esiste.','sys',650),M('«NON ENTRARE QUANDO IL LETTO È VUOTO.»','sys',650),M('Alzi gli occhi. Sul letto adesso non c’è più nemmeno la tua ombra.','sys')],choices:[C('Scatto una foto senza entrare.','room_evidence',true),D('Entro per controllare sotto il letto.','Ti chini. Sotto il letto vedi il corridoio di casa tua, ma dall’altra parte qualcuno è già inginocchiato e ti sta guardando.') ]},
room_evidence:{msgs:[M('Scatti la foto.','sys'),M('Nell’immagine il secondo telefono non compare.','sys',600),M('Al suo posto c’è una persona seduta sul bordo del letto, di spalle.','sys',700),M('Il numero sconosciuto riceve la foto prima ancora che tu possa inviarla.','them')],choices:[C('“Chi è quella persona?”','room_truth'),C('“Come hai ricevuto la foto?”','room_truth')]},
room_truth:{msgs:[M('Non guardarle il viso.','them'),M('Io l’ho fatto. È per questo che questa parte della notte per me finiva qui.','them',650),M('Tu invece hai una prova che io non avevo. Conservala.','them')],choices:[C('Esco dalla camera senza voltarmi.','room_close',true)]},
room_close:{msgs:[M('Chiudi lentamente la porta della camera.','sys'),M('Dall’altra parte qualcuno imita il rumore della serratura mezzo secondo dopo di te.','sys',700),M('La fotografia rimane sul telefono.','sys')],end:true},
wall_final:{msgs:[M('Torni alla parete.','sys'),M('Il ronzio è ancora lì, ma adesso pulsa a intervalli regolari.','sys',650),M('TOC. TOC. TOC. TOC.','sys',900),M('Quattro colpi. Non tre.','them')],choices:[C('Busso quattro volte nello stesso punto.','wall_four',true),C('Registro i quattro colpi.','wall_record',true),D('Appoggio l’occhio alla crepa.','La crepa non mostra l’interno del muro. Mostra il tuo corridoio, visto da un punto che non dovrebbe esistere. Qualcuno si avvicina dall’altra parte.') ]},
wall_four:{msgs:[M('Rispondi con quattro colpi.','sys'),M('Per qualche secondo non accade nulla.','sys',700),M('Poi la parete risponde una sola volta.','sys',900),M('Una crepa sottile compare sotto le tue nocche e comincia a salire.','sys',700)],choices:[C('Non la tocco. La filmo.','wall_evidence',true),D('Seguo la crepa con le dita.','La crepa si ferma sotto il tuo indice. Poi si apre di colpo lungo tutta la parete, come se qualcosa dall’altra parte avesse tirato.') ]},
wall_record:{msgs:[M('Avvii la registrazione.','sys'),M('I quattro colpi si ripetono. Questa volta il quarto arriva dal telefono, non dal muro.','sys',750),M('Sul display compare per un istante una chiamata dal tuo stesso numero.','sys')],choices:[C('Salvo la registrazione.','wall_evidence',true),D('Rispondo alla chiamata.','Dall’altoparlante senti quattro colpi. Il quarto arriva da dietro la tua testa.') ]},
wall_evidence:{msgs:[M('Salvi il video.','sys'),M('Riguardandolo, la crepa è già presente nel primo fotogramma.','sys',650),M('Tu ricordi perfettamente che non c’era.','sys'),M('Il numero sconosciuto ti invia lo stesso fotogramma con la data di domani.','them',700)],choices:[C('“Hai già bussato quattro volte?”','wall_truth'),C('“Cosa c’è dall’altra parte?”','wall_truth')]},
wall_truth:{msgs:[M('Io avevo sentito solo tre colpi.','them'),M('Il quarto è nuovo.','them',650),M('Questo significa che non stai ripetendo esattamente la mia notte.','them'),M('Conserva il video. È la prima cosa che hai trovato che io non ricordo.','them',650)],choices:[C('Mi allontano dalla parete.','wall_close',true)]},
wall_close:{msgs:[M('Ti allontani.','sys'),M('La crepa smette di crescere.','sys',650),M('Dopo qualche secondo senti quattro colpi molto lontani, come se provenissero da un altro appartamento.','sys',700)],end:true},
mirror_final:{msgs:[M('Torni in bagno senza accendere la luce.','sys'),M('La scritta “NON È LA PRIMA” è ancora sulla condensa.','sys',650),M('Ma sotto è comparsa una seconda riga.','sys'),M('“NON SEI L’ULTIMA.”','sys',700)],choices:[C('Fotografo lo specchio senza guardare il riflesso.','mirror_evidence',true),C('“L’hai scritto tu?”','mirror_question'),D('Guardo direttamente il mio riflesso.','Il tuo riflesso non ti guarda. Sta leggendo qualcosa sul telefono. Poi solleva lentamente gli occhi verso di te.') ]},
mirror_question:{msgs:[M('La prima frase sì.','them'),M('La seconda no.','them',650),M('Non guardare il centro dello specchio. Guarda soltanto il bordo.','them')],choices:[C('Guardo solo il bordo.','mirror_edge',true),C('Scatto una foto senza guardare.','mirror_evidence',true)]},
mirror_edge:{msgs:[M('Sul bordo inferiore dello specchio ci sono piccoli segni incisi nel vetro.','sys'),M('Sembrano tacche. Ne conti molte più di quante riesci a seguire.','sys',700),M('L’ultima è ancora pulita, come se fosse stata incisa pochi secondi fa.','sys')],choices:[C('Fotografo le tacche.','mirror_evidence',true),D('Tocco l’ultima tacca.','Nel momento in cui la tocchi, tutte le tacche compaiono sul tuo polso come graffi sottili.') ]},
mirror_evidence:{msgs:[M('Scatti la foto.','sys'),M('Nella galleria l’immagine appare capovolta, anche se non hai ruotato il telefono.','sys',650),M('Nel riflesso fotografato c’è una notifica che sul tuo schermo non è ancora arrivata.','sys',700),M('«HAI TROVATO UN’ALTRA USCITA.»','sys')],choices:[C('“Un’uscita da cosa?”','mirror_truth'),C('“Perché il messaggio è già nella foto?”','mirror_truth')]},
mirror_truth:{msgs:[M('Non lo so ancora.','them'),M('Ma questa foto non esiste nei miei ricordi.','them',650),M('Se la notte ricomincia, portala con te. Forse non dobbiamo sempre arrivare alla stessa porta.','them')],choices:[C('Conservo la foto.','mirror_close',true)]},
mirror_close:{msgs:[M('Blocchi lo schermo.','sys'),M('Quando lo riaccendi, la foto è ancora lì.','sys',650),M('Nello specchio, invece, la seconda frase è scomparsa.','sys')],end:true}
};
async function start(){if(S.started)return;S.started=true;S.startAt=Date.now();save();$('#overlay').classList.add('hidden');startClock();go('intro')}
const menuPanel=$('#menuPanel'),confirmPanel=$('#confirmPanel');let confirmAction=null;
$('#menuBtn').addEventListener('click',()=>menuPanel.classList.remove('hidden'));
$('#menuClose').addEventListener('click',()=>menuPanel.classList.add('hidden'));
function ask(kind){menuPanel.classList.add('hidden');confirmAction=kind;$('#confirmTitle').textContent=kind==='all'?'CANCELLARE TUTTO?':'RIAVVIARE IL LOOP?';$('#confirmText').textContent=kind==='all'?'Cancella anche i progressi conservati tra i loop. Non può essere annullato.':'Usalo se la partita sembra bloccata. Il loop corrente ripartirà dalle 00:01:00.';$('#confirmYes').textContent=kind==='all'?'CANCELLA TUTTO':'RIAVVIA';confirmPanel.classList.remove('hidden')}
$('#loopReset').addEventListener('click',()=>ask('loop'));$('#fullReset').addEventListener('click',()=>ask('all'));
$('#confirmNo').addEventListener('click',()=>{confirmPanel.classList.add('hidden');confirmAction=null});
$('#confirmYes').addEventListener('click',()=>{const a=confirmAction;confirmPanel.classList.add('hidden');a==='all'?resetAll():resetLoop()});
$('#start').addEventListener('click',start);$('#restart').addEventListener('click',resetLoop);
$('#notify').addEventListener('click',async()=>{try{if(!('Notification'in window))throw 0;const p=await Notification.requestPermission();$('#notify').textContent=p==='granted'?'NOTIFICHE ATTIVE':'NOTIFICHE NON DISPONIBILI'}catch(_){$('#notify').textContent='NOTIFICHE NON DISPONIBILI'}});
window.addEventListener('error',()=>{});
// Una partita lasciata a metà viene riavviata in modo pulito: niente ricostruzioni parziali della chat.
try{const old=JSON.parse(localStorage.getItem(KEY));if(old&&old.started&&!old.chapterDone&&!old.ending){localStorage.removeItem(KEY)}}catch(_){localStorage.removeItem(KEY)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});
