'use strict';
const $=s=>document.querySelector(s), chat=$('#chat'), choices=$('#choices'), clock=$('#clock');
const KEY='nonaprire_v010_state', META='nonaprire_meta';
const START=60, END=48*60, LIMIT=(END-START)*1000;
let S={started:false,alive:true,ending:false,chapterDone:false,startAt:0,node:'intro',history:[],loops:0};
let clockTimer=null, deadlineTimer=null, busy=false, deathTimer=null;
try{const m=JSON.parse(localStorage.getItem(META));if(m&&Number.isFinite(m.loops))S.loops=m.loops}catch(_){}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch(_){}}
function elapsed(){return S.started?Math.max(0,Date.now()-S.startAt):0}
function gameSec(){return Math.min(END,START+Math.floor(elapsed()/1000))}
function fmt(n){const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return [h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
function updateClock(){clock.textContent=fmt(gameSec());if(S.started&&S.alive&&!S.ending&&!S.chapterDone&&elapsed()>=LIMIT)deadlineDeath()}
function startClock(){clearInterval(clockTimer);clearTimeout(deadlineTimer);clockTimer=setInterval(updateClock,250);deadlineTimer=setTimeout(deadlineDeath,Math.max(0,LIMIT-elapsed()+50));updateClock()}
function stopTimers(){clearInterval(clockTimer);clearTimeout(deadlineTimer);if(deathTimer)clearInterval(deathTimer);clockTimer=deadlineTimer=deathTimer=null}
function scrollBottom(){requestAnimationFrame(()=>chat.scrollTop=chat.scrollHeight)}
function add(text,who='sys',delay=0){return new Promise(resolve=>setTimeout(()=>{if(!text){resolve();return}const d=document.createElement('div');d.className='msg '+who;d.textContent=text;chat.appendChild(d);scrollBottom();resolve()},delay))}
function clearChoices(){choices.replaceChildren()}
function renderChoices(list){clearChoices();if(S.ending||S.chapterDone)return;for(const c of list){const b=document.createElement('button');b.type='button';b.className='choice '+(c.action?'action':'');b.textContent=c.label;b.addEventListener('click',()=>pick(c),{once:true});choices.appendChild(b)}}
async function pick(c){if(busy||S.ending||S.chapterDone)return;busy=true;const label=c.label;clearChoices();S.history.push({node:S.node,choice:label,at:gameSec()});save();await add(label,'me',0);if(c.death){busy=false;return die(c.death)}if(c.end){busy=false;return chapterEnd()}busy=false;return go(c.next)}
async function go(id){if(S.ending||S.chapterDone)return;const node=NODES[id];if(!node){return failSafe('Il filo della conversazione si interrompe. Il telefono vibra una volta, poi compare un nuovo messaggio.')}S.node=id;save();clearChoices();for(const m of node.msgs){await add(m.text,m.who||'sys',m.delay??420)}if(node.end)return chapterEnd();if(!node.choices||node.choices.length===0)return failSafe('Per qualche secondo non succede nulla. Poi il numero sconosciuto scrive di nuovo.');renderChoices(node.choices)}
async function failSafe(text){await add(text,'sys',500);await add('Non restare fermo. Vai verso l’ingresso.','them',450);renderChoices([{label:'Vado verso l’ingresso.',action:true,next:'entry_final'},{label:'Resto dove sono e ascolto.',action:true,next:'listen_final'}])}
function contextualDeadline(){const n=S.node;if(/bed|room|mirror/.test(n))return 'Alle 00:48 lo schermo nella camera si accende. Nel vetro nero compare il tuo riflesso, ma continua a muoversi quando tu ti fermi.';if(/door|entry/.test(n))return 'Alle 00:48 la serratura scatta. Non dall’esterno. La porta si apre lentamente verso di te e, dietro, c’è il corridoio di casa tua.';if(/wall|listen|ceiling/.test(n))return 'Alle 00:48 i colpi tornano. Non arrivano più dalla parete: arrivano da dentro il telefono che tieni in mano.';return 'Alle 00:48 tutti i rumori cessano. Nel display vedi per un istante qualcuno fermo esattamente alle tue spalle.'}
async function deadlineDeath(){if(!S.started||!S.alive||S.ending||S.chapterDone)return;await die(contextualDeadline())}
async function die(text){if(S.ending||S.chapterDone)return;S.ending=true;S.alive=false;clearChoices();clearTimeout(deadlineTimer);save();await add(text,'sys',450);const box=document.createElement('div');box.className='deadBattery';box.innerHTML='<div class="deadBatteryRow"><span class="deadBatteryIcon" aria-hidden="true">🪫</span><div><strong>BATTERIA SCARICA</strong><span>0%</span></div></div><p class="deathCountdown">Il loop ricomincia tra <b>15</b> secondi…</p><small>Puoi scorrere la chat e rileggere cosa è successo.</small>';chat.appendChild(box);scrollBottom();let left=15;const n=box.querySelector('b');deathTimer=setInterval(()=>{left--;if(n)n.textContent=Math.max(0,left);if(left<=0){clearInterval(deathTimer);deathTimer=null;resetLoop()}},1000)}
async function chapterEnd(){if(S.chapterDone||S.ending)return;S.chapterDone=true;clearChoices();stopTimers();save();await add('Il telefono smette di vibrare. Per la prima volta dall’inizio della notte, il silenzio non sembra una minaccia.','sys',600);const box=document.createElement('div');box.className='chapterEnd';box.innerHTML='<strong>CAPITOLO 1 COMPLETATO</strong><p>Per questa notte, non puoi andare oltre.</p><small>Continua nel Capitolo 2 — in sviluppo</small>';chat.appendChild(box);scrollBottom();const b=document.createElement('button');b.type='button';b.className='choice';b.textContent='RICOMINCIA IL CAPITOLO 1';b.addEventListener('click',resetLoop,{once:true});choices.appendChild(b)}
function resetLoop(){stopTimers();const loops=(S.loops||0)+1;try{localStorage.setItem(META,JSON.stringify({loops}))}catch(_){}localStorage.removeItem(KEY);location.reload()}
function resetAll(){stopTimers();localStorage.removeItem(KEY);localStorage.removeItem(META);location.reload()}
const C=(label,next,action=false)=>({label,next,action});
const D=(label,death,action=true)=>({label,death,action});
const M=(text,who='sys',delay=420)=>({text,who,delay});
const NODES={
intro:{msgs:[M('NON APRIRE.','them',650),M('Controlla la porta d’ingresso. Assicurati che sia chiusa.','them',650)],choices:[C('“Chi sei?”','who'),C('“Perché?”','why'),C('Controllo la porta.','door_check',true),C('Ignoro il messaggio.','ignore',true)]},
who:{msgs:[M('Non importa ancora.','them'),M('Tra poco sentirai tre colpi. Se la porta non è chiusa, non avremo molto tempo.','them',600)],choices:[C('“Come fai a saperlo?”','knows'),C('Controllo la porta.','door_check',true),C('Aspetto i colpi.','wait_knock',true)]},
why:{msgs:[M('Perché tra poco sentirai tre colpi.','them'),M('Qualunque voce sentirai dopo, non aprire.','them')],choices:[C('Controllo la porta.','door_check',true),C('Aspetto i colpi.','wait_knock',true),C('Provo a chiamare il 112.','call_112',true)]},
knows:{msgs:[M('Perché li ho già aspettati.','them'),M('La prima volta ho aperto.','them',550)],choices:[C('“La prima volta?”','first_time'),C('Controllo la porta.','door_check',true)]},
first_time:{msgs:[M('Non posso spiegartelo in un messaggio.','them'),M('Prima ascolta i colpi. Poi decidi se credermi.','them')],choices:[C('Controllo la porta.','door_check',true),C('Resto fermo e aspetto.','wait_knock',true)]},
call_112:{msgs:[M('Nessun servizio.','sys'),M('Il numero sconosciuto scrive prima che tu possa riprovare.','sys'),M('La rete non ti aiuterà stanotte.','them')],choices:[C('“Come lo sai?”','knows'),C('Controllo la porta.','door_check',true),D('Apro la porta e cerco aiuto.','La maniglia scende prima che tu riesca a toccarla. La porta si apre verso l’interno. Dall’altra parte non c’è il pianerottolo.') ]},
door_check:{msgs:[M('La porta è chiusa a chiave.','sys'),M('TOC.  TOC.  TOC.','sys',1100),M('Allontanati dalla porta.','them')],choices:[C('Guardo dallo spioncino.','peephole',true),C('“Chi è?”','voice'),C('Mi allontano in silenzio.','back_away',true)]},
wait_knock:{msgs:[M('Aspetti.','sys'),M('TOC.  TOC.  TOC.','sys',1200),M('Adesso sai che non stavo indovinando.','them')],choices:[C('Guardo dallo spioncino.','peephole',true),C('“Chi è?”','voice'),C('Mi allontano in silenzio.','back_away',true)]},
ignore:{msgs:[M('Posi il telefono.','sys'),M('TOC.  TOC.  TOC.','sys',1200),M('Il telefono vibra di nuovo.','sys'),M('NON APRIRE.','them')],choices:[C('Guardo dallo spioncino.','peephole',true),C('Mi allontano dalla porta.','back_away',true),D('Apro e faccio finire questa storia.','La porta si apre senza resistenza. Sul pianerottolo non c’è nessuno. Poi senti la porta chiudersi alle tue spalle.') ]},
peephole:{msgs:[M('Avvicini l’occhio allo spioncino.','sys'),M('Il pianerottolo è vuoto. Ma la luce davanti alla tua porta è spenta. Tutte le altre sono accese.','sys',650),M('Non guardare una seconda volta.','them')],choices:[C('Mi allontano.','hall_a',true),C('“Perché non devo guardare?”','proof'),D('Guardo di nuovo.','Lo spioncino è completamente nero. Poi qualcosa batte tre volte sul vetro, dall’interno.') ]},
voice:{msgs:[M('“Chi è?”','sys'),M('Dall’altra parte arriva la tua voce.','sys',700),M('«Sono io. Aprimi.»','sys',600),M('Non risponderle.','them')],choices:[C('Mi allontano senza parlare.','hall_a',true),C('“Sei tu quello fuori?”','proof'),D('“Dimmi qualcosa che solo io so.”','La voce dietro la porta risponde con una frase che ricordi di aver pensato, ma mai detto. La serratura scatta.') ]},
back_away:{msgs:[M('Ti allontani. I colpi cessano.','sys'),M('Dal fondo della casa arriva una vibrazione breve.','sys',700)],choices:[C('Controllo il corridoio.','hall_a',true),C('“Adesso dimmi chi sei.”','proof')]},
proof:{msgs:[M('Se te lo dicessi adesso, penseresti che sto mentendo.','them'),M('Vai in bagno. Guarda lo specchio, ma non accendere la luce.','them',600)],choices:[C('Vado in bagno.','bathroom',true),C('Non mi fido. Controllo il corridoio.','hall_a',true)]},
hall_a:{msgs:[M('Il corridoio è vuoto.','sys'),M('La porta della camera da letto è socchiusa. Prima era chiusa.','sys',650)],choices:[C('Guardo dentro senza entrare.','bed_glance',true),C('Vado in bagno.','bathroom',true),C('Cerco da dove arriva la vibrazione.','wall',true)]},
bathroom:{msgs:[M('Il bagno è buio. Nello specchio distingui appena il tuo viso.','sys'),M('Il telefono vibra.','sys'),M('Guarda la tua mano sinistra.','them')],choices:[C('Guardo la mano.','hand',true),C('Esco subito dal bagno.','hall_b',true)]},
hand:{msgs:[M('Sul polso c’è un graffio sottile che non ricordi di esserti fatto.','sys'),M('Sul bordo dello specchio, nella condensa, qualcuno ha scritto: “NON È LA PRIMA”.','sys',700)],choices:[C('“Sei stato tu?”','identity'),C('Esco e controllo la camera.','bed_glance',true)]},
identity:{msgs:[M('Sì. Ma non stanotte.','them'),M('Sono te. Non quello che sei adesso.','them',650),M('Non devi credermi. Devi solo ricordare quello che vedi.','them')],choices:[C('“Cosa devo ricordare?”','remember'),C('Non gli credo. Esco dal bagno.','hall_b',true)]},
remember:{msgs:[M('Quale porta cambia posizione. Da dove arrivano i colpi. E cosa stai facendo quando l’orologio smette di essere dalla tua parte.','them')],choices:[C('Controllo la camera da letto.','bed_glance',true),C('Cerco la vibrazione nel muro.','wall',true)]},
wall:{msgs:[M('Appoggi l’orecchio alla parete.','sys'),M('Senti un ronzio basso, come un telefono in vibrazione molto lontano.','sys',650),M('Poi tre colpi si spostano lungo il muro, verso la camera.','sys',700)],choices:[C('Seguo i colpi.','bed_glance',true),C('Mi sposto nella direzione opposta.','hall_b',true),C('Appoggio il telefono alla parete.','wall_phone',true)]},
wall_phone:{msgs:[M('Appoggi il telefono al muro.','sys'),M('Lo schermo si accende da solo. Per un istante compare una chiamata in uscita verso il tuo stesso numero.','sys',700),M('La chiamata termina prima che tu possa toccare nulla.','sys')],choices:[C('Vado verso la camera.','bed_glance',true),C('Vado verso l’ingresso.','entry_final',true)]},
bed_glance:{msgs:[M('Dalla soglia vedi il letto.','sys'),M('Sopra le coperte c’è un secondo telefono acceso.','sys',650),M('Sul suo schermo è aperta la stessa conversazione.','sys',600)],choices:[C('Resto sulla soglia e leggo lo schermo.','second_phone',true),C('Mi allontano dalla camera.','hall_b',true),D('Entro e prendo il secondo telefono.','Appena tocchi il secondo telefono, quello nella tua mano si spegne. Dal corridoio arriva la tua voce: «Finalmente.»') ]},
second_phone:{msgs:[M('Sullo schermo dell’altro telefono c’è un messaggio non ancora arrivato sul tuo.','sys'),M('«Quando senti la sedia, non guardare in alto.»','sys',650),M('Un secondo dopo, dal soffitto arriva il rumore di una sedia trascinata.','sys',850)],choices:[C('Non guardo in alto e torno nel corridoio.','hall_b',true),C('“Cosa c’è sopra di me?”','ceiling_answer'),D('Guardo il soffitto.','Una crepa compare esattamente sopra di te. Si apre come una palpebra. Qualcosa dall’altra parte guarda giù.') ]},
ceiling_answer:{msgs:[M('Nel mio appartamento non c’era niente.','them'),M('Nel tuo, adesso, non ne sono più sicuro.','them',600)],choices:[C('Mi allontano dalla camera.','hall_b',true),C('Vado verso l’ingresso.','entry_final',true)]},
hall_b:{msgs:[M('Le luci del corridoio si spengono una alla volta.','sys'),M('L’ultima rimasta accesa è quella vicino all’ingresso.','sys',700),M('Il numero sconosciuto scrive una sola frase.','sys'),M('Adesso scegli dove vuoi essere quando cambia tutto.','them')],choices:[C('Vado verso l’ingresso.','entry_final',true),C('Resto nel corridoio e ascolto.','listen_final',true),C('Torno davanti alla camera.','room_final',true)]},
entry_final:{msgs:[M('Raggiungi l’ingresso. La porta è ancora chiusa.','sys'),M('Sotto la porta scivola lentamente un foglio.','sys',700),M('È una fotografia del tuo corridoio. È stata scattata da dietro di te.','sys',700)],choices:[C('Non mi volto. Fotografo a mia volta il foglio.','evidence',true),D('Mi volto subito.','Il corridoio è vuoto. Nella fotografia, invece, ora sei girato verso l’obiettivo. E qualcuno è dietro di te.'),C('“Cosa devo fare con questa foto?”','evidence')]},
listen_final:{msgs:[M('Rimani fermo.','sys'),M('Senti due respirazioni: la tua e una seconda, sincronizzata con mezzo secondo di ritardo.','sys',750),M('Quando trattieni il fiato, l’altra continua.','sys',650)],choices:[C('Registro il suono con il telefono.','evidence',true),C('Mi muovo lentamente verso l’ingresso.','entry_final',true),D('Chiamo ad alta voce chiunque sia lì.','La seconda respirazione si interrompe. Una voce, vicinissima al tuo orecchio, risponde: «Eccomi.»')]},
room_final:{msgs:[M('Torni davanti alla camera. Il secondo telefono non è più sul letto.','sys'),M('Adesso è sul pavimento del corridoio, alle tue spalle.','sys',700)],choices:[C('Non lo tocco. Scatto una foto.','evidence',true),C('Mi allontano verso l’ingresso.','entry_final',true),D('Raccolgo il secondo telefono.','Lo schermo mostra la tua chat un messaggio avanti. Leggi: «Non raccoglierlo.» Poi senti le dita chiudersi attorno al tuo polso.') ]},
evidence:{msgs:[M('Salvi la prova sul telefono.','sys'),M('Per alcuni secondi non succede nulla.','sys',650),M('Poi il numero sconosciuto invia un file.','sys'),M('È la stessa prova che hai appena creato. Ma il timestamp è di domani.','them',700)],choices:[C('“Come hai questo file?”','file_origin'),C('Controllo i dettagli del file.','file_details',true),C('Non apro il file.','refuse_file',true)]},
file_origin:{msgs:[M('Non l’ho creato io.','them'),M('L’ho trovato sul mio telefono quando tutto è ricominciato.','them',650),M('C’era anche una cosa che non avevo mai visto prima.','them')],choices:[C('“Cosa?”','file_warning'),C('Controllo comunque i dettagli.','file_details',true)]},
file_details:{msgs:[M('Apri le informazioni del file.','sys'),M('Data: domani. Ora: 00:47:51.','sys',650),M('Posizione: nessuna. Dispositivo: il tuo telefono.','sys'),M('In fondo compare una riga che non dovrebbe esserci: “2 di 2”.','sys',650)],choices:[C('Cerco il primo file.','first_file',true),C('“Cosa significa 2 di 2?”','file_warning')]},
refuse_file:{msgs:[M('Lasci il file chiuso.','sys'),M('Dopo qualche secondo compare una nuova anteprima, senza che tu la tocchi.','sys',650),M('È una fotografia della porta d’ingresso. Scattata dall’interno di casa.','sys')],choices:[C('Controllo la porta senza avvicinarmi.','door_return',true),C('“Smettila di mandarmi foto.”','sender_push')]},
sender_push:{msgs:[M('Non sono io.','them'),M('Da questo momento, se ricevi qualcosa senza che io scriva prima, non aprirlo.','them',650)],choices:[C('“Allora chi lo manda?”','file_warning'),C('Controllo la porta.','door_return',true)]},
file_warning:{msgs:[M('Non lo so.','them'),M('Ma la prima volta che ho visto “2 di 2”, subito dopo ho trovato un file che non ricordavo di aver registrato.','them',650),M('Se c’è anche sul tuo telefono, non riprodurlo ad alto volume.','them')],choices:[C('Cerco il primo file.','first_file',true),C('Vado verso la porta.','door_return',true)]},
first_file:{msgs:[M('Nella cartella compare un secondo elemento.','sys'),M('Non ha immagine. Solo una durata: 00:08.','sys',650),M('Il nome del file è “ASCOLTA_PRIMA”.','sys')],choices:[C('Lo riproduco al minimo volume.','audio_low',true),D('Lo riproduco ad alto volume.','Dall’altoparlante escono tre colpi. La casa li ripete nello stesso istante, da ogni parete. Poi qualcosa risponde dal corridoio.'),C('Non lo riproduco. Controllo la porta.','door_return',true)]},
audio_low:{msgs:[M('Abbassi il volume quasi a zero.','sys'),M('Per otto secondi senti solo fruscio.','sys',650),M('Poi, appena prima che finisca, riconosci la tua voce: «Quando la porta si apre, non attraversarla.»','sys',850)],choices:[C('“Quella voce sono io.”','voice_confirm'),C('Controllo la porta d’ingresso.','door_return',true)]},
voice_confirm:{msgs:[M('Sì.','them'),M('Ed è la prima cosa che mi hai mandato tu.','them',650),M('Solo che tu non l’hai ancora registrata.','them')],choices:[C('“Quando dovrei registrarla?”','record_rule'),C('Vado alla porta.','door_return',true)]},
record_rule:{msgs:[M('Non lo so.','them'),M('Per me era già lì. Per te non lo è ancora.','them'),M('Qualcosa sta cambiando l’ordine.','them',650)],choices:[C('Controllo la porta.','door_return',true),C('Resto fermo e ascolto la casa.','house_listen',true)]},
house_listen:{msgs:[M('Trattieni il respiro.','sys'),M('La casa è immobile.','sys',550),M('Poi senti una chiave girare nella serratura dell’ingresso. Molto lentamente.','sys',800)],choices:[C('Vado verso l’ingresso senza fare rumore.','door_return',true),C('Mi chiudo nella stanza più vicina.','hide_room',true)]},
hide_room:{msgs:[M('Entri nella stanza più vicina e accosti la porta.','sys'),M('Dal corridoio arriva il rumore della porta d’ingresso che si apre.','sys',750),M('Nessun passo. Solo il suono di un messaggio ricevuto. Non sul tuo telefono.','sys',800)],choices:[C('Resto nascosto e guardo il mio schermo.','door_open_msg',true),D('Apro la porta della stanza per vedere.','Nel corridoio c’è qualcuno con il tuo telefono in mano. Alza lo sguardo nello stesso momento in cui lo fai tu.') ]},
door_return:{msgs:[M('Torni a vedere l’ingresso da lontano.','sys'),M('La chiave gira da sola.','sys',700),M('La porta si apre di pochi centimetri. Dietro non c’è il pianerottolo: c’è di nuovo il tuo corridoio.','sys',850)],choices:[C('Non attraverso la porta.','door_open_msg',true),D('Attraverso la porta.','Fai un passo oltre la soglia. Ti ritrovi alle tue spalle, un istante prima. La porta si chiude tra le due versioni di te.'),C('Chiudo la porta senza guardare oltre.','close_impossible',true)]},
close_impossible:{msgs:[M('Allunghi una mano verso la porta.','sys'),M('Prima che tu la tocchi, dall’altro corridoio una mano identica alla tua fa lo stesso gesto.','sys',750),M('Entrambe vi fermate.','sys')],choices:[C('Ritraggo la mano.','door_open_msg',true),D('Tocco la mano dall’altra parte.','Per un istante non senti più quale delle due mani sia la tua. Poi il telefono cade a terra dall’altro lato della soglia.') ]},
door_open_msg:{msgs:[M('Il telefono vibra.','sys'),M('Numero sconosciuto: «Non attraversarla.»','them',550),M('Subito sotto compare un secondo messaggio. Stesso numero.','sys',650),M('«È troppo tardi. Fallo adesso.»','them',650)],choices:[C('“Quale dei due sei tu?”','two_senders'),C('Non rispondo a nessuno dei due.','silence_choice',true)]},
two_senders:{msgs:[M('Il primo messaggio scompare.','sys'),M('Poi arriva una risposta: «Quello che ti ha detto di non aprire.»','them',700),M('Dall’altro lato della porta, il tuo telefono suona.','sys',700)],choices:[C('Non attraverso. Registro la mia voce.','record_future',true),C('Chiudo la conversazione e resto fermo.','silence_choice',true)]},
silence_choice:{msgs:[M('Non rispondi.','sys'),M('Per qualche secondo nessuno scrive.','sys',650),M('Poi il telefono dall’altro lato della soglia riproduce una registrazione a volume bassissimo.','sys'),M('È la tua voce. Le parole sono quasi le stesse che hai appena sentito.','sys',750)],choices:[C('Registro anch’io il messaggio.','record_future',true),C('Mi allontano dalla soglia.','final_retreat',true)]},
record_future:{msgs:[M('Apri il registratore.','sys'),M('Per un istante non sai cosa dire. Poi pronunci lentamente: «Quando la porta si apre, non attraversarla.»','sys',850),M('La registrazione dura esattamente otto secondi.','sys',650),M('Sul display compare da sola la scritta: “1 di 2”.','sys',700)],choices:[C('Invio il file al numero sconosciuto.','send_file',true),C('Lo tengo sul telefono.','final_retreat',true)]},
send_file:{msgs:[M('Premi invio.','sys'),M('Il messaggio resta senza spunta.','sys',600),M('Poi scompare dalla conversazione.','sys'),M('Numero sconosciuto: «Adesso so da dove veniva.»','them',750)],choices:[C('“Quindi sono stato io a mandartelo?”','last_truth'),C('Mi allontano dalla porta.','final_retreat',true)]},
final_retreat:{msgs:[M('Ti allontani dalla soglia senza attraversarla.','sys'),M('La porta resta aperta sul corridoio impossibile.','sys',650),M('Dall’altra parte, una figura fa esattamente lo stesso passo indietro.','sys',700),M('Il telefono vibra un’ultima volta.','sys')],choices:[C('Leggo il messaggio.','last_truth',true)]},
last_truth:{msgs:[M('Non so se io sia il tuo domani o solo un altro tentativo.','them'),M('Ma questa è la prima volta che il file parte da te.','them',650),M('Qualcosa è cambiato.','them'),M('Se la notte ricomincia, ricordati della porta. E ricordati che non tutti i miei messaggi potrebbero essere miei.','them',750)],choices:[{label:'Continuo a leggere.',next:'chapter_close',action:true}]},
chapter_close:{msgs:[M('La conversazione resta aperta.','sys'),M('La porta impossibile si richiude lentamente.','sys',650),M('Sul telefono rimane una sola cosa che prima non c’era: la registrazione di otto secondi.','sys',700)],end:true}
};
async function start(){if(S.started)return;S.started=true;S.startAt=Date.now();save();$('#overlay').classList.add('hidden');startClock();go('intro')}
const menuPanel=$('#menuPanel'),confirmPanel=$('#confirmPanel');let confirmAction=null;
$('#menuBtn').addEventListener('click',()=>menuPanel.classList.remove('hidden'));
$('#menuClose').addEventListener('click',()=>menuPanel.classList.add('hidden'));
function ask(kind){menuPanel.classList.add('hidden');confirmAction=kind;$('#confirmTitle').textContent=kind==='all'?'CANCELLARE TUTTO?':'RIAVVIARE IL LOOP?';$('#confirmText').textContent=kind==='all'?'Cancella anche i progressi conservati tra i loop. Non può essere annullato.':'Usalo se la partita sembra bloccata. Il loop corrente ripartirà dalle 00:01:00.';$('#confirmYes').textContent=kind==='all'?'CANCELLA TUTTO':'RIAVVIA';confirmPanel.classList.remove('hidden')}
$('#loopReset').addEventListener('click',()=>ask('loop'));$('#fullReset').addEventListener('click',()=>ask('all'));
$('#confirmNo').addEventListener('click',()=>{confirmPanel.classList.add('hidden');confirmAction=null});
$('#confirmYes').addEventListener('click',()=>{const a=confirmAction;confirmPanel.classList.add('hidden');a==='all'?resetAll():resetLoop()});
$('#start').addEventListener('click',start);$('#restart').addEventListener('click',resetLoop);
$('#notify').addEventListener('click',async()=>{try{if(!('Notification'in window))throw 0;const p=await Notification.requestPermission();$('#notify').textContent=p==='granted'?'NOTIFICHE ATTIVE':'NOTIFICHE NON DISPONIBILI'}catch(_){$('#notify').textContent='NOTIFICHE NON DISPONIBILI'}});
window.addEventListener('error',e=>{const d=document.createElement('div');d.className='msg sys danger';d.textContent='Errore interno: '+e.message;chat.appendChild(d)});
// Una partita lasciata a metà viene riavviata in modo pulito: niente ricostruzioni parziali della chat.
try{const old=JSON.parse(localStorage.getItem(KEY));if(old&&old.started&&!old.chapterDone&&!old.ending){localStorage.removeItem(KEY)}}catch(_){localStorage.removeItem(KEY)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});
